//mongoimport --host Cluster0-shard-0/cluster0-shard-00-00-hube8.mongodb.net:27017,cluster0-shard-00-01-hube8.mongodb.net:27017,cluster0-shard-00-02-hube8.mongodb.net:27017 --ssl --username covid19ngr --password covid19ngr --authenticationDatabase admin --db covid19data --collection timelines --type json --file ~/myjson.json --fields
const cases_time_line = [
    {
        dailyConfirmed: 1,
        dailyDeceased: 0,
        dailyRecovered: 0,
        date: '2020-02-27',
        totalConfirmed: 1,
        totalDeath: 0,
        totalDischarged: 0,
    },
    {
        dailyConfirmed: 0,
        dailyDeceased: 0,
        dailyRecovered: 0,
        date: '2020-02-28',
        totalConfirmed: 1,
        totalDeath: 0,
        totalDischarged: 0,
    },
    {
        dailyConfirmed: 0,
        dailyDeceased: 0,
        dailyRecovered: 0,
        date: '2020-02-29',
        totalConfirmed: 1,
        totalDeath: 0,
        totalDischarged: 0,
    },
    {
        dailyConfirmed: 0,
        dailyDeceased: 0,
        dailyRecovered: 0,
        date: '2020-03-01',
        totalConfirmed: 1,
        totalDeath: 0,
        totalDischarged: 0,
    },
    {
        dailyConfirmed: 0,
        dailyDeceased: 0,
        dailyRecovered: 0,
        date: '2020-03-02',
        totalConfirmed: 1,
        totalDeath: 0,
        totalDischarged: 0,
    },
    {
        dailyConfirmed: 0,
        dailyDeceased: 0,
        dailyRecovered: 0,
        date: '2020-03-03',
        totalConfirmed: 1,
        totalDeath: 0,
        totalDischarged: 0,
    },
    {
        dailyConfirmed: 0,
        dailyDeceased: 0,
        dailyRecovered: 0,
        date: '2020-03-04',
        totalConfirmed: 1,
        totalDeath: 0,
        totalDischarged: 0,
    },
    {
        dailyConfirmed: 0,
        dailyDeceased: 0,
        dailyRecovered: 0,
        date: '2020-03-05',
        totalConfirmed: 1,
        totalDeath: 0,
        totalDischarged: 0,
    },
    {
        dailyConfirmed: 0,
        dailyDeceased: 0,
        dailyRecovered: 0,
        date: '2020-03-06',
        totalConfirmed: 1,
        totalDeath: 0,
        totalDischarged: 0,
    },
    {
        dailyConfirmed: 0,
        dailyDeceased: 0,
        dailyRecovered: 0,
        date: '2020-03-07',
        totalConfirmed: 1,
        totalDeath: 0,
        totalDischarged: 0,
    },
    {
        dailyConfirmed: 0,
        dailyDeceased: 0,
        dailyRecovered: 0,
        date: '2020-03-08',
        totalConfirmed: 1,
        totalDeath: 0,
        totalDischarged: 0,
    },
    {
        dailyConfirmed: 1,
        dailyDeceased: 0,
        dailyRecovered: 0,
        date: '2020-03-09',
        totalConfirmed: 2,
        totalDeath: 0,
        totalDischarged: 0,
    },
    {
        dailyConfirmed: 1,
        dailyDeceased: 0,
        dailyRecovered: 0,
        date: '2020-03-10',
        totalConfirmed: 2,
        totalDeath: 0,
        totalDischarged: 0,
    },
    {
        dailyConfirmed: 1,
        dailyDeceased: 0,
        dailyRecovered: 0,
        date: '2020-03-11',
        totalConfirmed: 2,
        totalDeath: 0,
        totalDischarged: 0,
    },
    {
        dailyConfirmed: 1,
        dailyDeceased: 0,
        dailyRecovered: 0,
        date: '2020-03-12',
        totalConfirmed: 2,
        totalDeath: 0,
        totalDischarged: 0,
    },
    {
        dailyConfirmed: 0,
        dailyDeceased: 0,
        dailyRecovered: 1,
        date: '2020-03-13',
        totalConfirmed: 1,
        totalDeath: 0,
        totalDischarged: 1,
    },
    {
        dailyConfirmed: 0,
        dailyDeceased: 0,
        dailyRecovered: 1,
        date: '2020-03-14',
        totalConfirmed: 1,
        totalDeath: 0,
        totalDischarged: 1,
    },
    {
        dailyConfirmed: 0,
        dailyDeceased: 0,
        dailyRecovered: 1,
        date: '2020-03-15',
        totalConfirmed: 1,
        totalDeath: 0,
        totalDischarged: 1,
    },
    {
        dailyConfirmed: 0,
        dailyDeceased: 0,
        dailyRecovered: 1,
        date: '2020-03-16',
        totalConfirmed: 1,
        totalDeath: 0,
        totalDischarged: 1,
    },
    {
        dailyConfirmed: 1,
        dailyDeceased: 0,
        dailyRecovered: 0,
        date: '2020-03-17',
        totalConfirmed: 2,
        totalDeath: 0,
        totalDischarged: 1,
    },
    {
        dailyConfirmed: 5,
        dailyDeceased: 0,
        dailyRecovered: 0,
        date: '2020-03-18',
        totalConfirmed: 7,
        totalDeath: 0,
        totalDischarged: 1,
    },
    {
        dailyConfirmed: 4,
        dailyDeceased: 0,
        dailyRecovered: 0,
        date: '2020-03-19',
        totalConfirmed: 11,
        totalDeath: 0,
        totalDischarged: 1,
    },
    {
        dailyConfirmed: 1,
        dailyDeceased: 0,
        dailyRecovered: 0,
        date: '2020-03-20',
        totalConfirmed: 12,
        totalDeath: 0,
        totalDischarged: 1,
    },
    {
        dailyConfirmed: 10,
        dailyDeceased: 0,
        dailyRecovered: 0,
        date: '2020-03-21',
        totalConfirmed: 22,
        totalDeath: 0,
        totalDischarged: 1,
    },
    {
        dailyConfirmed: 8,
        dailyDeceased: 0,
        dailyRecovered: 2,
        date: '2020-03-22',
        totalConfirmed: 30,
        totalDeath: 0,
        totalDischarged: 2,
    },
    {
        dailyConfirmed: 6,
        dailyDeceased: 1,
        dailyRecovered: 0,
        date: '2020-03-23',
        totalConfirmed: 36,
        totalDeath: 1,
        totalDischarged: 2,
    },
    {
        dailyConfirmed: 8,
        dailyDeceased: 0,
        dailyRecovered: 0,
        date: '2020-03-24',
        totalConfirmed: 44,
        totalDeath: 1,
        totalDischarged: 2,
    },
    {
        dailyConfirmed: 7,
        dailyDeceased: 0,
        dailyRecovered: 0,
        date: '2020-03-25',
        totalConfirmed: 51,
        totalDeath: 1,
        totalDischarged: 2,
    },
    {
        dailyConfirmed: 14,
        dailyDeceased: 0,
        dailyRecovered: 0,
        date: '2020-03-26',
        totalConfirmed: 65,
        totalDeath: 1,
        totalDischarged: 2,
    },
    {
        dailyConfirmed: 16,
        dailyDeceased: 0,
        dailyRecovered: 1,
        date: '2020-03-27',
        totalConfirmed: 81,
        totalDeath: 1,
        totalDischarged: 3,
    },
    {
        dailyConfirmed: 16,
        dailyDeceased: 0,
        dailyRecovered: 0,
        date: '2020-03-28',
        totalConfirmed: 97,
        totalDeath: 1,
        totalDischarged: 3,
    },
    {
        dailyConfirmed: 14,
        dailyDeceased: 0,
        dailyRecovered: 0,
        date: '2020-03-29',
        totalConfirmed: 111,
        totalDeath: 1,
        totalDischarged: 3,
    },
    {
        dailyConfirmed: 20,
        dailyDeceased: 1,
        dailyRecovered: 5,
        date: '2020-03-30',
        totalConfirmed: 131,
        totalDeath: 2,
        totalDischarged: 8,
    },
    {
        dailyConfirmed: 20,
        dailyDeceased: 0,
        dailyRecovered: 1,
        date: '2020-03-31',
        totalConfirmed: 151,
        totalDeath: 2,
        totalDischarged: 9,
    },
    {
        dailyConfirmed: 23,
        dailyDeceased: 0,
        dailyRecovered: 0,
        date: '2020-04-01',
        totalConfirmed: 174,
        totalDeath: 2,
        totalDischarged: 9,
    },
    {
        dailyConfirmed: 10,
        dailyDeceased: 0,
        dailyRecovered: 11,
        date: '2020-04-02',
        totalConfirmed: 184,
        totalDeath: 2,
        totalDischarged: 20,
    },
    {
        dailyConfirmed: 25,
        dailyDeceased: 2,
        dailyRecovered: 5,
        date: '2020-04-03',
        totalConfirmed: 209,
        totalDeath: 4,
        totalDischarged: 25,
    },
    {
        dailyConfirmed: 5,
        dailyDeceased: 0,
        dailyRecovered: 0,
        date: '2020-04-04',
        totalConfirmed: 214,
        totalDeath: 4,
        totalDischarged: 25,
    },
    {
        dailyConfirmed: 18,
        dailyDeceased: 1,
        dailyRecovered: 8,
        date: '2020-04-05',
        totalConfirmed: '232',
        totalDeath: 5,
        totalDischarged: 33,
    },
    {
        dailyConfirmed: 6,
        dailyDeceased: 0,
        dailyRecovered: 2,
        date: '2020-04-06',
        totalConfirmed: 238,
        totalDeath: 5,
        totalDischarged: 35,
    },
    {
        dailyConfirmed: 16,
        dailyDeceased: 1,
        dailyRecovered: 9,
        date: '2020-04-07',
        totalConfirmed: 254,
        totalDeath: 6,
        totalDischarged: 44,
    },
    {
        dailyConfirmed: 20,
        dailyDeceased: 0,
        dailyRecovered: 0,
        date: '2020-04-08',
        totalConfirmed: 274,
        totalDeath: 4,
        totalDischarged: 44,
    },
    {
        dailyConfirmed: 14,
        dailyDeceased: 1,
        dailyRecovered: 7,
        date: '2020-04-09',
        totalConfirmed: 288,
        totalDeath: 7,
        totalDischarged: 51,
    },
    {
        dailyConfirmed: 17,
        dailyDeceased: 0,
        dailyRecovered: 7,
        date: '2020-04-10',
        totalConfirmed: 305,
        totalDeath: 7,
        totalDischarged: 58,
    },
    {
        dailyConfirmed: 13,
        dailyDeceased: 3,
        dailyRecovered: 12,
        date: '2020-04-11',
        totalConfirmed: 318,
        totalDeath: 10,
        totalDischarged: 70,
    },
    {
        dailyConfirmed: 5,
        dailyDeceased: 0,
        dailyRecovered: 15,
        date: '2020-04-12',
        totalConfirmed: 323,
        totalDeath: 10,
        totalDischarged: 85,
    },
    {
        dailyConfirmed: 20,
        dailyDeceased: 0,
        dailyRecovered: 6,
        date: '2020-04-13',
        totalConfirmed: 343,
        totalDeath: 10,
        totalDischarged: 91,
    },
    {
        dailyConfirmed: 30,
        dailyDeceased: 1,
        dailyRecovered: 7,
        date: '2020-04-14',
        totalConfirmed: 373,
        totalDeath: 11,
        totalDischarged: 98,
    },
    {
        dailyConfirmed: 34,
        dailyDeceased: 1,
        dailyRecovered: 30,
        date: '2020-04-15',
        totalConfirmed: 407,
        totalDeath: 12,
        totalDischarged: 128,
    },
    {
        dailyConfirmed: 35,
        dailyDeceased: 1,
        dailyRecovered: 24,
        date: '2020-04-16',
        totalConfirmed: 442,
        totalDeath: 13,
        totalDischarged: 152,
    },
    {
        dailyConfirmed: 51,
        dailyDeceased: 4,
        dailyRecovered: 7,
        date: '2020-04-17',
        totalConfirmed: 493,
        totalDeath: 17,
        totalDischarged: 159,
    },
    {
        dailyConfirmed: 48,
        dailyDeceased: 2,
        dailyRecovered: 7,
        date: '2020-04-18',
        totalConfirmed: 541,
        totalDeath: 19,
        totalDischarged: 166,
    },
    {
        dailyConfirmed: 86,
        dailyDeceased: 2,
        dailyRecovered: 4,
        date: '2020-04-19',
        totalConfirmed: 627,
        totalDeath: 21,
        totalDischarged: 170,
    },
    {
        dailyConfirmed: 38,
        dailyDeceased: 1,
        dailyRecovered: 18,
        date: '2020-04-20',
        totalConfirmed: 665,
        totalDeath: 22,
        totalDischarged: 188,
    },
    {
        dailyConfirmed: 117,
        dailyDeceased: 3,
        dailyRecovered: 9,
        date: '2020-04-21',
        totalConfirmed: 782,
        totalDeath: 25,
        totalDischarged: 197,
    },
    {
        dailyConfirmed: 91,
        dailyDeceased: 3,
        dailyRecovered: 0,
        date: '2020-04-22',
        totalConfirmed: 873,
        totalDeath: 28,
        totalDischarged: 197,
    },
    {
        dailyConfirmed: 108,
        dailyDeceased: 3,
        dailyRecovered: 0,
        date: '2020-04-23',
        totalConfirmed: 981,
        totalDeath: 31,
        totalDischarged: 197,
    },
    {
        dailyConfirmed: 114,
        dailyDeceased: 1,
        dailyRecovered: 11,
        date: '2020-04-24',
        totalConfirmed: 1095,
        totalDeath: 32,
        totalDischarged: 208,
    },
    {
        dailyConfirmed: 87,
        dailyDeceased: 3,
        dailyRecovered: 14,
        date: '2020-04-25',
        totalConfirmed: 1182,
        totalDeath: 35,
        totalDischarged: 222,
    },
    {
        dailyConfirmed: 91,
        dailyDeceased: 5,
        dailyRecovered: 17,
        date: '2020-04-26',
        totalConfirmed: 1273,
        totalDeath: 40,
        totalDischarged: 239,
    },
    {
        dailyConfirmed: 64,
        dailyDeceased: 0,
        dailyRecovered: 16,
        date: '2020-04-27',
        totalConfirmed: 1337,
        totalDeath: 40,
        totalDischarged: 255,
    },
    {
        dailyConfirmed: 195,
        dailyDeceased: 4,
        dailyRecovered: 0,
        date: '2020-04-28',
        totalConfirmed: 1532,
        totalDeath: 44,
        totalDischarged: 255,
    },
    {
        dailyConfirmed: 196,
        dailyDeceased: 7,
        dailyRecovered: 52,
        date: '2020-04-29',
        totalConfirmed: 1728,
        totalDeath: 51,
        totalDischarged: 307,
    },
    {
        dailyConfirmed: 204,
        dailyDeceased: 7,
        dailyRecovered: 12,
        date: '2020-04-30',
        totalConfirmed: 1932,
        totalDeath: 58,
        totalDischarged: 319,
    },
    {
        dailyConfirmed: 238,
        dailyDeceased: 10,
        dailyRecovered: 32,
        date: '2020-05-01',
        totalConfirmed: 2170,
        totalDeath: 68,
        totalDischarged: 351,
    },
    {
        dailyConfirmed: 220,
        dailyDeceased: 17,
        dailyRecovered: 34,
        date: '2020-05-02',
        totalConfirmed: 2388,
        totalDeath: 85,
        totalDischarged: 385,
    },
    {
        dailyConfirmed: 170,
        dailyDeceased: 2,
        dailyRecovered: 15,
        date: '2020-05-03',
        totalConfirmed: 2558,
        totalDeath: 87,
        totalDischarged: 400,
    },
    {
        dailyConfirmed: 244,
        dailyDeceased: 6,
        dailyRecovered: 17,
        date: '2020-05-04',
        totalConfirmed: 2802,
        totalDeath: 93,
        totalDischarged: 417,
    },
];
module.exports = cases_time_line;
